# Generated by Django 4.1.5 on 2023-02-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='project',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vote_total',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
