version: '3'
services:
  django-web:
    build: .
    container_name: portfolio-website
    ports:
      - "8000:8000"
    restart: always
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    networks:
      - portfolio_network

  nginx-server:
    container_name: portfolio-nginx
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./nginx/logs:/var/log/nginx 
    depends_on:
      - django-web
    networks:
      - portfolio_network
    ports:
      - "8001:80"


  ngrok-service:
    container_name: portfolio-ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/.config/ngrok/ngrok.yml"
    volumes:
      - ./.ngrok.yml:/etc/.config/ngrok/ngrok.yml
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - nginx-server
    networks:
      - portfolio_network
    ports:
      - 4040:4040

networks:
  portfolio_network:
    name: portfolio_network